name: Build Faso Tricycle APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Installer Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Construire l'APK
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Publier l'APK
        uses: actions/upload-artifact@v4
        with:
          name: Faso-Tricycle-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
